version: '3.1'

services:
  db:
    image: mysql:5.7.34
    build:
      context: .
      dockerfile: Dockerfile.mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - "./mysql-data:/var/lib/mysql"
    command: mysqld --sql_mode=""
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8070:80
    environment:
      - PMA_ARBITRARY=1
