version: '3.1'

services:
  zellij:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ./CRITERIA:/Zellij/CRITERIA
      - ./ZellijData:/Zellij/ZellijData
      - ./instance:/Zellij/instance
      - ./secret:/Zellij/secret
      - ./website:/Zellij/website
  db:
    image: mysql:5.7.34
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - "./mysql-data:/var/lib/mysql"
    command: mysqld --sql_mode=""    
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8070:80
    environment:
      - PMA_ARBITRARY=1